### ISSUE TITLE
List institutes in alphabetical order

### ISSUE THREAD

**Issue by AmooHashem** [Kamva-Academy/Kamva-Platform-Frontend#18]
تو داشبورد، لیست مدارس رو به ترتیب حروف الفبا نشون بدیم. لازم نیست از سمت بک باشه، تو همین فرانت هندلش کنیم.

**Comment by Imanm02** [comment]
I sorted the institutes' names by sorting the JS array in StudentProfile.js.
All institutes' names and types are sorted.
