### ISSUE TITLE
Add countDown timer for send verify code buttons

### ISSUE THREAD

**Issue by AmooHashem** [Kamva-Academy/Kamva-Platform-Frontend#9]
به جای «یک دقیقه صبر کن» یه تایمر بیاد و ۱ دقیقه بشماره و وقتی صفر شد، دکمه فعال بشه

![](http://s6.uplod.ir/i/01012/sbtunio0ak0i.png)

**Comment by ptechofficial** [comment]
Can i work on this?

**Comment by AmooHashem** [comment]
@ptechofficial 
Its really late, but we still need it :)
You are welcome to do this! but pay attention that our working branch is "refactor-after-zero"
